# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

name: Print Subpackages

on:
  workflow_dispatch:
    inputs:
      subpackages_str:
        description: 'Subpackages to be built individually (e.g. config ec2)'
        default: '*'
        required: true
        type: string
      provider:
        description: 'Provider repo'
        default: 'ulucinar/upbound-provider-azure'
        required: true
        type: string

jobs:
  get_subpackages:
    uses: ./.github/workflows/get-subpackages.yml
    with:
      provider: ${{ inputs.provider }}
      ref: main
      subpackages_str: ${{ inputs.subpackages_str }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  print_calculated:
    runs-on: ubuntu-latest
    needs: get_subpackages
    steps:
      - name: Print Subpackages
        run: |
          echo "Calculated subpackages: ${{ needs.get_subpackages.outputs.subpackages }}"
